name: Kotlin Build and Publish Library

on:
  workflow_call:
    inputs:
      java-version:
        description: 'Java version to use'
        required: false
        type: string
        default: '21'

permissions:
  contents: read
  packages: write

jobs:
  build-test-publish:
    runs-on: ubuntu-latest
    
    steps:
    - name: Checkout code
      uses: actions/checkout@v4
      with:
        submodules: true
      
    - name: Verify Maven wrapper exists
      run: |
        if [ ! -f "./mvnw" ]; then
          echo "Error: Maven wrapper (mvnw) not found in repository"
          exit 1
        fi
      
    - name: Set up JDK
      uses: actions/setup-java@v4
      with:
        java-version: ${{ inputs.java-version }}
        distribution: 'temurin'
        
    - name: Cache Maven dependencies
      uses: actions/cache@v3
      with:
        path: ~/.m2
        key: ${{ runner.os }}-m2-${{ hashFiles('**/pom.xml') }}
        restore-keys: ${{ runner.os }}-m2
        
    - name: Make Maven wrapper executable
      run: chmod +x ./mvnw
      
    - name: Configure Maven settings for GitHub Packages
      run: |
        mkdir -p ~/.m2
        cat > ~/.m2/settings.xml << 'EOF'
        <settings>
          <servers>
            <server>
              <id>github</id>
              <username>${env.GITHUB_ACTOR}</username>
              <password>${env.GITHUB_TOKEN}</password>
            </server>
          </servers>
        </settings>
        EOF
      
    - name: Build project
      run: ./mvnw clean compile
      
    - name: Run tests
      run: ./mvnw test
      
    - name: Package artifact
      run: ./mvnw package -DskipTests
      
    - name: Publish to GitHub Packages
      run: ./mvnw deploy -DskipTests -DaltDeploymentRepository=github::https://maven.pkg.github.com/${{ github.repository }}
      env:
        GITHUB_TOKEN: ${{ github.token }}